#!/usr/bin/env python
#coding:utf-8
import rospy
from std_msgs.msg import String
 
def callBack(data):
    print data
 
if __name__ == '__main__':
    nodeName = 'subscriber_py'
    rospy.init_node(nodeName)
    topicName = 'data_topic'
    subscriber = rospy.Subscriber(topicName,String,callBack)  #從topic獲取string再呼叫callback
    rospy.spin()
